/* @flow */
// Sagas
export const LOGIN_USER_REQUESTED = 'LOGIN_USER_REQUESTED';
export const SEARCH_PHRASE_REQUESTED = 'SEARCH_PHRASE_REQUESTED';
export const FETCH_DOCUMENTS_REQUESTED = 'FETCH_DOCUMENTS_REQUESTED';
// App
export const CLEAR_SEARCHED_PHRASE = 'CLEAR_SEARCHED_PHRASE';
export const CHANGE_SEARCHED_PHRASE = 'CHANGE_SEARCHED_PHRASE';
// Auth
export const FETCH_USER_STARTED = 'FETCH_USER_STARTED';
export const FETCH_USER_SUCCEEDED = 'FETCH_USER_SUCCEEDED';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';
export const FETCH_USER_FINISHED = 'FETCH_USER_FINISHED';
// Documents
export const FETCH_DOCUMENTS_STARTED = 'FETCH_DOCUMENTS_STARTED';
export const FETCH_DOCUMENTS_SUCCEEDED = 'FETCH_DOCUMENTS_SUCCEEDED';
export const FETCH_DOCUMENTS_FINISHED = 'FETCH_DOCUMENTS_FINISHED';
export const FETCH_DOCUMENTS_FAILED = 'FETCH_DOCUMENTS_FAILED';
